<div class="row-fluid">
    <!-- block -->
    <div class="block">
        <div class="navbar navbar-inner block-header">
            <div class="muted pull-left"><?php print $this->titulo; ?></div>
        </div>
        <div class="block-content collapse in">
            <div class="span12">
                <div class="table-toolbar">
                    <div class="btn-group">
                        <a href="<?php print URL; ?>pagamento/novo"><button class="btn btn-success">Novo Pagamento <i class="icon-plus icon-white"></i></button></a>
                    </div>
                    <div class="btn-group pull-right">
                        <button data-toggle="dropdown" class="btn dropdown-toggle">Opções <span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li><a href="#">Imprimir</a></li>
                            <li><a href="#">Salvar PDF</a></li>
                            <li><a href="#">Exportar para Excel</a></li>
                        </ul>
                    </div>
                </div>

                <table  class="table table-striped table-bordered">   
                    <thead>
                        <tr>
                            <th>Nome</th> 
                            <th>Mes</th>
                            <th>Data</th>
                            <th>Codigo</th>
                            <th>Factura</th>
                        </tr>
                    </thead>

                    <tbody>
                        <?php if (isset($this->pagamentos) && !empty($this->pagamentos)): ?>
                            <?php foreach ($this->pagamentos as $valor): ?>

                                <tr>
                                    <td><?php print $valor['nome']; ?></td>
                                    <td><?php print $valor['mes']; ?></td>
                                    <td><?php print $valor['data']; ?></td>
                                    <td><?php print $valor['codigo']; ?></td>
                                    <td><a rel="<?php print $valor['id_cliente']; ?>" href="<?php print URL . "pdf/factura/" . $valor['mes']."/".$valor['id_cliente'] ?>" id="contrato"><i class="">Imprimir</i></a></td>

                                </tr>
                            <?php endforeach; ?>

                        </tbody>
                    </table>
                <?php else: ?>
                    <h2 class="text-center">Não Foi efectuado nenhum pagamento</h2>
                <?php endif; ?>


                <?php if (isset($this->paginacion) && !empty($this->paginacion)) echo $this->paginacion; ?>

            </div>
        </div>
    </div>
    <!-- /block -->
</div>
<hr>