<?php $mes=array('janeiro','feveiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro');?>


<div class="span10 " id="content" style="margin-left: 300px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-right">Dados do  Pagamento</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <!-- BEGIN FORM-->
                    <form action="<?php print URL; ?>pagamento" id="form_sample_1" class="form-horizontal" method="POST">
                        <fieldset>
                            <div class="control-group">
                                <label class="control-label">Codigo do Cliente<span class="required">*</span></label>
                                <div class="controls">
                                    <input name="codigo" type="number" class="span6 m-wrap"/>
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">Mes<span class="required">*</span></label>
                                <div class="controls">
                                    <select name="mes" >
                                        <?php foreach ($mes as $valor):?>
                                        <option value="<?php print $valor;?>"><?php print $valor;?></option>
                                        <?php endforeach;?>
                                    </select>
                                </div>
                            </div>
                            <input name="enviar" type="hidden" value="1"/>
                            <div class="form-actions">
                                <button type="submit" class="btn btn-primary">Salvar Dados</button>
                                <button type="reset" class="btn">Cancelar</button>
                            </div>
                        </fieldset>
                    </form>
                    <!-- END FORM-->
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
    <!-- /validation -->

</div>
</div>