
<div class="row-fluid">
    <!-- block -->
    <div class="block">
        <div class="navbar navbar-inner block-header">
            <div class="muted pull-left">Estatistica</div>
            <div class="pull-right"><span class="badge badge-warning">Representção Grafica</span>

            </div>
        </div>
        <div class="block-content collapse in">
            <div class="span3">
                <div class="chart" data-percent="73">73%</div>
                <div class="chart-bottom-heading"><span class="label label-info">Pagamentos Mensas</span>

                </div>
            </div>
        </div>
    </div>
</div>
<!-- /block -->

<div class="row-fluid">
    <?php if (Session::nivelViewRestrito(array('admin'))): ?>
        <div class="span6">
            <!-- block -->
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left"><?php print $this->titulo; ?></div>
                    <div class="pull-right"><span class="badge badge-info">1,234</span>

                    </div>
                </div>
                <div class="block-content collapse in">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Nome</th>
                                <th>Login</th>
                                <th>Nivel</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->usuarios as $u): ?>
                                <tr>
                                    <td><?php print $u['id_usuario'] ?></td>
                                    <td><?php print $u['nome']; ?></td>
                                    <td><?php print $u['login']; ?></td>
                                    <td><?php print $u['nivel']; ?></td>
                                </tr>

                            <?php endforeach; ?>

                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /block -->
              <?php endif; ?>
        </div>
  

    <div class="span6">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Pagamentos</div>
                <div class="pull-right"><span class="badge badge-info">752</span>

                </div>
            </div>
            <div class="block-content collapse in">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Mes</th>
                            <th>Data</th>
                            <th>Usuario</th>
                        </tr>
                    </thead>
                    <tbody>
                       
                        <?php //print_r($this->pagamentos); exit;
                        foreach ($this->pagamentos as $u): ?>
                            <tr>
                                <td><?php print $u['id'] ?></td>
                                <td><?php print $u['mes']; ?></td>
                                <td><?php print $u['data']; ?></td>
                                <td><?php print $u['nome']; ?></td>
                            </tr>

                        <?php endforeach; ?>

                    </tbody>
                </table>
            </div>
        </div>
        <!-- /block -->
    </div>
    <div class="row-fluid pull-left">
        <div class="span6">
            <!-- block -->
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Clientes</div>
                    <div class="pull-right"><span class="badge badge-info">17</span>

                    </div>
                </div>
                <div class="block-content collapse in">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Nome</th>
                                <th>Telefone</th>
                                <th>Morada</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->clientes as $u): ?>
                                <tr>
                                    <td><?php print $u['id'] ?></td>
                                    <td><?php print $u['nome']; ?></td>
                                    <td><?php print $u['telefone']; ?></td>
                                    <td><?php print $u['morada']; ?></td>
                                </tr>

                            <?php endforeach; ?>

                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /block -->
        </div>


    </div>
</div>
</div>
</div>
