
<div class="row-fluid">
                <!-- block -->
                <div class="block">
                    <div class="navbar navbar-inner block-header">
                        <div class="muted pull-left">Estatistica</div>
                        <div class="pull-right"><span class="badge badge-warning">Representção Grafica</span>

                        </div>
                    </div>
                    <div class="block-content collapse in">
                        <div class="span3">
                            <div class="chart" data-percent="73">73%</div>
                            <div class="chart-bottom-heading"><span class="label label-info">Pagamentos Mensas</span>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /block -->

            <div class="row-fluid">
               <?php if (Session::nivelViewRestrito(array('admin'))): ?>
                <div class="span6">
                    <!-- block -->
                    <div class="block">
                        <div class="navbar navbar-inner block-header">
                            <div class="muted pull-left"><?php print $this->titulo;?></div>
                            <div class="pull-right"><span class="badge badge-info">1,234</span>

                            </div>
                        </div>
                        <div class="block-content collapse in">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Nome</th>
                                        <th>Login</th>
                                        <th>Nivel</th>
                                    </tr>
                                </thead>
                                <tbody>
                                     <?php foreach ($this->usuarios as $u):?>
                                    <tr>
                                        <td><?php print $u['id_usuario']?></td>
                                        <td><?php print $u['nome'];?></td>
                                         <td><?php print $u['login'];?></td>
                                         <td><?php print $u['nivel'];?></td>
                                    </tr>
                                   
                                     <?php endforeach;?>
                               
                               </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- /block -->
                </div>
                <?php endif;?>

                <div class="span6">
                    <!-- block -->
                    <div class="block">
                        <div class="navbar navbar-inner block-header">
                            <div class="muted pull-left">Pagamentos</div>
                            <div class="pull-right"><span class="badge badge-info">752</span>

                            </div>
                        </div>
                        <div class="block-content collapse in">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Mes</th>
                                        <th>Data</th>
                                        <th>Valor</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>1</td>
                                        <td>Coat</td>
                                        <td>02/02/2013</td>
                                        <td>$25.12</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>Coat</td>
                                        <td>02/02/2013</td>
                                        <td>$25.12</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>Coat</td>
                                        <td>02/02/2013</td>
                                        <td>$25.12</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- /block -->
                </div>
                <div class="row-fluid">
                <div class="span6">
                            <!-- block -->
                            <div class="block">
                                <div class="navbar navbar-inner block-header">
                                    <div class="muted pull-left">Clients</div>
                                    <div class="pull-right"><span class="badge badge-info">17</span>

                                    </div>
                                </div>
                                <div class="block-content collapse in">
                                    <table class="table table-striped">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>First Name</th>
                                                <th>Last Name</th>
                                                <th>Username</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>1</td>
                                                <td>Mark</td>
                                                <td>Otto</td>
                                                <td>@mdo</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <!-- /block -->
                        </div>
                
                <div class="span6">
                    <!-- block -->
                    <div class="block">
                        <div class="navbar navbar-inner block-header">
                            <div class="muted pull-left">Clientes com Dividas</div>
                            <div class="pull-right"><span class="badge badge-info">812</span>

                            </div>
                        </div>
                        <div class="block-content collapse in">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Nome</th>
                                        <th>Mes</th>
                                        <th>Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>1</td>
                                        <td>02/02/2013</td>
                                        <td>$25.12</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- /block -->
                </div>
            </div>
            </div>
        </div>
    </div>
