
<div class="row-fluid" id="cliente">
    <!-- block -->
    <div class="block">
        <div class="navbar navbar-inner block-header">
            <div class="muted pull-right"><?php print $this->titulo; ?></div>
        </div>
        <div class="block-content collapse in">
            <div class="span12">

                <form action="<?php print URL; ?>sms/novo" id="form_sample_1" class="form-horizontal" method="POST">
                    <fieldset>

                        <div class="control-group">
                            <label class="control-label" >Telefone</label>
                            <div class="controls">
                                <div class="btn-group">
                                    <select id="example21" multiple="multiple" name="telefone[]">
                                        <?php foreach ($this->nome as $teste): ?>
                                            <option value="<?php print $teste['telefone']; ?>"><?php print $teste['nome']; ?></option>  
                                        <?php endforeach; ?>
                                    </select>
                                    <button id="example21-toggle" class="btn btn-primary">Select All</button>
                                </div>                        </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="textarea2">Mensagem</label>
                            <div class="controls">
                                <textarea class="input-xlarge textarea" placeholder="Escreva sua mensagem" style="width: 810px; height: 200px" name="mensagem"></textarea>
                            </div>
                        </div>


                        <input name="enviar" type="hidden" value="1"/>
                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary">Enviar Mensagem</button>
                            <button type="reset" class="btn">Cancelar</button>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
    <!-- /block -->
</div>
</div>
</div>
<hr>
