
<?php if (isset($this->dados) and ! empty($this->dados)): ?>

    <div class="span10 " id="content" style="margin-left: 300px;">
        <!-- validation -->
        <div class="row-fluid">
            <!-- block -->
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-right">Dados do Cliente</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <!-- BEGIN FORM-->
                        <form  id="form_sample_1" class="form-horizontal" method="POST">
                            <fieldset>

                                <input name="envia" type="hidden" value="1" />
                                <div class="control-group">
                                    <label class="control-label">Nome<span class="required">*</span></label>
                                    <div class="controls">
                                        <input name="nome" type="text" class="span6 m-wrap" value="<?php print $this->dados['nome']; ?>"/>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label">Morada<span class="required">*</span></label>
                                    <div class="controls">
                                        <input name="morada" type="text" class="span6 m-wrap" value="<?php print $this->dados['morada']; ?>"/>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label">Contacto<span class="required">*</span></label>
                                    <div class="controls">
                                        <input name="telefone" type="tel" class="span6 m-wrap" value="<?php print $this->dados['telefone']; ?>"/>

                                    </div>
                                </div>

                                <div class="form-actions">
                                    <button type="submit" class="btn btn-primary">Salvar Dados</button>
                                    <button type="reset" class="btn">Cancelar</button>
                                </div>

                            </fieldset>
                        </form>
                        <!-- END FORM-->
                    </div>
                </div>
            </div>
            <!-- /block -->
        </div>
        <!-- /validation -->

    </div>
    </div>
<?php endif; ?>