
<div class="row-fluid" id="cliente">
    <!-- block -->
    <div class="block">
        <div class="navbar navbar-inner block-header">
            <div class="muted pull-left"><?php print $this->titulo; ?></div>
        </div>
        <div class="block-content collapse in">
            <div class="span12">
                <div class="table-toolbar">
                    <div class="btn-group">
                        <a href="<?php print URL; ?>cliente/novo"><button class="btn btn-success" id="">Adiconar Novo <i class="icon-plus icon-white"></i></button></a>
                    </div>
                    <div class="btn-group pull-right">
                        <button data-toggle="dropdown" class="btn dropdown-toggle">Opções <span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li><a href="<?php print URL; ?>pdf/cliente">Exportar Pdf</a></li>
                        </ul>
                    </div>
                </div>

                <table  class="table table-striped table-bordered">   
                    <thead>
                        <tr>

                            <th>Nome</th> 
                            <th>Morada</th>
                            <th>Contacto</th>
                            <th>Alterar</th>
                            <th>Apagar</th>
                            <th>Contrato</th>
                        </tr>
                    </thead>

                    <tbody>
                        <?php if (isset($this->clientes) && !empty($this->clientes)): ?>
                            <?php foreach ($this->clientes as $valor): ?>

                                <tr>
                                    <td><?php print $valor['nome']; ?></td>
                                    <td><?php print $valor['morada']; ?></td>
                                    <td><?php print $valor['telefone']; ?></td>

                                    <td><a rel="<?php print $valor['id']; ?>" href="<?php print URL . "cliente/editar/" . $valor['id']; ?>" id="altera"><i class="">Alterar</i></a></td>
                                    <td><a rel="<?php print $valor['id']; ?>" href="<?php print URL . "cliente/apagar/" . $valor['id']; ?>" id="delete"><i class="">Apagar</i></a></td>
                                    <td><a rel="<?php print $valor['codigo']; ?>" href="<?php print URL . "pdf/contrato/" . $valor['codigo']; ?>" id="contrato"><i class="">Imprimir</i></a></td>
                                </tr>
                            <?php endforeach; ?>

                        </tbody>
                    </table>
                <?php else: ?>
                    <h2 class="text-center alert-error">Não existe nenhuma usuario cadastrado</h2>
                <?php endif; ?>

                <?php if (isset($this->paginacion) && !empty($this->paginacion)) echo $this->paginacion; ?>

            </div>
        </div>
    </div>
    <!-- /block -->
</div>
</div>
</div>
<hr>
