<div class="row-fluid">
    <!-- block -->
    <div class="block">
        <div class="navbar navbar-inner block-header">
            <div class="muted pull-left"><?php print $this->titulo; ?></div>
        </div>
        <div class="block-content collapse in">
            <div class="span12">
                <div class="table-toolbar">
                    <div class="btn-group">
                        <a href="<?php print URL . $this->link; ?>"><button class="btn btn-success">Novo Usuario <i class="icon-plus icon-white"></i></button></a>
                    </div>
                    <div class="btn-group pull-right">
                        <button data-toggle="dropdown" class="btn dropdown-toggle">Opções <span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li><a href="#">Imprimir</a></li>
                            <li><a href="#">Salvar PDF</a></li>
                            <li><a href="#">Exportar para Excel</a></li>
                        </ul>
                    </div>
                </div>

                <table  class="table table-striped table-bordered">   
                    <thead>
                        <tr>
                            <th>Nome</th> 
                            <th>Login</th>
                            <th>Nivel</th>
                            <th>Alterar</th>
                            <th>Apagar</th>
                        </tr>
                    </thead>

                    <tbody>
                        <?php if (isset($this->usuarios) && !empty($this->usuarios)): ?>
                            <?php foreach ($this->usuarios as $valor): ?>

                                <tr>
                                    <td><?php print $valor['nome']; ?></td>
                                    <td><?php print $valor['login']; ?></td>
                                    <td><?php print $valor['nivel']; ?></td>
                                    <td><a rel="<?php print $valor['id_usuario']; ?>" href="<?php print URL . "usuario/editar/" . $valor['id_usuario']; ?>" id="altera"><i class="">Alterar</i></a></td>
                                    <td><a rel="<?php print $valor['id_usuario']; ?>" href="<?php print URL . "usuario/apagar/" . $valor['id_usuario']; ?>" id="delete"><i class="">Apagar</i></a></td>


                                </tr>
                            <?php endforeach; ?>

                        </tbody>
                    </table>
                <?php else: ?>
                    <h2 class="text-center text-error">Nenhum usuario cadastrado</h2>
                <?php endif; ?>

                <?php if (!isset($this->paginacion) && !empty($this->paginacion)) echo $this->paginacion; ?>



            </div>
        </div>
    </div>
    <!-- /block -->
</div>
<hr>