<div class="span10 " id="content" style="margin-left: 300px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-right">Dados do Usuario</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <!-- BEGIN FORM-->
                    <form action="<?php print URL; ?>usuario" id="form_sample_1" class="form-horizontal" method="POST">
                        <fieldset>
                            <div class="control-group">
                                <label class="control-label">Nome<span class="required">*</span></label>
                                <div class="controls">
                                    <input name="nome" type="text" class="span6 m-wrap"/>
                                </div>
                            </div>
                            
                            
                            <div class="control-group">
                                <label class="control-label">Login<span class="required">*</span></label>
                                <div class="controls">
                                    <input name="login" type="text" class="span6 m-wrap"/>
                                </div>
                            </div>
                            
                            <div class="control-group">
                                <label class="control-label">Senha<span class="required">*</span></label>
                                <div class="controls">
                                    <input name="senha" type="password" class="span6 m-wrap"/>
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">Mes<span class="required">*</span></label>
                                <div class="controls">
                                    <select name="nivel" >
                                        <option value="usuario">Usuario</option>
                                        <option value="admin">Admin</option>
                                    </select>
                                </div>
                            </div>
                            <input name="enviar" type="hidden" value="1"/>
                            <div class="form-actions">
                                <button type="submit" class="btn btn-primary">Salvar Dados</button>
                                <button type="reset" class="btn">Cancelar</button>
                            </div>
                        </fieldset>
                    </form>
                    <!-- END FORM-->
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
    <!-- /validation -->

</div>
</div>